[build]
  # Diz ao Netlify para entrar na pasta frontend na hora do build
  base = "frontend"

  # Publica a pasta /frontend/public (como o site)
  publish = "public"

  # Copia tudo de /frontend/src para /frontend/public/src
  # (assim os caminhos /src/js/gate.js e /src/css/... existem no site publicado)
  command = "mkdir -p public/src && cp -R src/* public/src/"
